version: "3.8"

services:
  aprcroso:
    image: aprcroso
    hostname: aprcoso
    build:
      context: .
      dockerfile: ./aprcoso/Dockerfile
    restart: always
    environment:
      PORT: 8004
      MONGO_DB_URI: mongodb://root:pass@mongo:27017
    ports:
      - "8004:8004"
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - auth_log:/auth
    networks:
      - network

  auth-service:
    image: auth-service
    hostname: auth-service
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    restart: always
    environment:
      PORT: 8000
      MONGO_DB_URI: mongodb://root:pass@mongo:27017
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - auth_log:/auth
    networks:
      - network

  mongo:
    image: mongo
    hostname: mongo
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mongoDemo
    # Docker health check - checks if the database is "alive"
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - mongo_store:/data/db
    networks:
      - network

  # NoSQL: MongoExpress
  mongo-express:
    image: mongo-express
    restart: always
    environment:
      # hostname of the mongo database
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    volumes:
      - mongo_express_data:/data/db
    networks:
      - network

volumes:
  mongo_store:
  mongo_express_data:
  auth_log:

networks:
  network:
    driver: bridge
